security:
    encoders:
        bcrypt:
            algorithm: bcrypt
            cost: 12
            
        md5:
            algorithm: md5
            encode_as_base64: false
            iterations: 1
            
    providers:
        novosga_provider:
            id: App\Security\UserProvider
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        oauth_token:
            pattern:    ^/api/token
            security:   false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false

        login:
            pattern:  ^/login$
            anonymous: ~

        main:
            provider: novosga_provider
            security: true
            anonymous: false
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /


    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
