language: php

dist: trusty
sudo: false

php:
    - 7.1

git:
    depth: 1

env:
    global:
        - LANGUAGE="en"
        - APP_ENV="prod"
        - DATABASE_URL="mysql://root@127.0.0.1:3306/db?charset=utf8mb4&serverVersion=5.7"
        - DATABASE_PASS="just-to-build"
        - COMPOSER_ROOT_VERSION="2.0.x-dev"

install:
    - travis_retry composer update --prefer-dist

script:
    - vendor/bin/phpcs
    - phpunit

cache:
    directories:
        - $HOME/.composer/cache