language: php

dist: trusty
sudo: false

php:
    - 7.1

git:
    depth: 1

addons:
    apt_packages:
        - libicu-dev
        - libxml2-dev
        - zlib1g-dev

env:
    - APP_ENV: 'prod'
    - DATABASE_URL: 'mysql://root@127.0.0.1:3306/db?charset=utf8mb4&serverVersion=5.7'
    - DATABASE_PASS: 'just-to-build'
    - COMPOSER_ROOT_VERSION: 2.0.x-dev

  
install: travis_retry composer update --prefer-dist --no-dev

cache:
    directories:
        - $HOME/.composer/cache