Novosga\Entity\Configuracao:
    type: entity
    table: config
    id:
        namespace:
            type: string
            length: 30
            id: true
        name:
            type: string
            length: 30
            id: true
    fields:
        value:
            type: text
        type:
            type: integer
