Novosga\Entity\Lotacao:
    type: entity
    table: lotacoes
    repositoryClass: App\Repository\ORM\LotacaoRepository
    # MySQL 5.7 bug: https://github.com/symfony/symfony/issues/23768
    uniqueConstraints:
        lotacao_usuario_unidade_idx:
          columns: [ usuario_id, unidade_id ]
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    manyToOne:
        usuario:
            targetEntity: Novosga\Entity\Usuario
            cascade: {  }
            fetch: LAZY
            inversedBy: lotacoes
            joinColumns:
                usuario_id:
                    referencedColumnName: id
        unidade:
            targetEntity: Novosga\Entity\Unidade
            cascade: {  }
            fetch: LAZY
            joinColumns:
                unidade_id:
                    referencedColumnName: id
        perfil:
            targetEntity: Novosga\Entity\Perfil
            cascade: {  }
            fetch: LAZY
            joinColumns:
                perfil_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
