Novosga\Entity\Unidade:
    type: entity
    table: unidades
    repositoryClass: App\Repository\ORM\UnidadeRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    embedded:
        impressao:
            class: Novosga\Entity\ConfiguracaoImpressao
    fields:
        codigo:
            type: string
            length: 10
            unique: true
            nullable: false
        nome:
            type: string
            length: 50
            unique: false
            nullable: false
        ativo:
            type: boolean
            nullable: false
        createdAt:
            type: datetime
            column: created_at
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: true
    lifecycleCallbacks: {  }
    entityListeners:
        App\Listener\ORM\UnidadeListener: ~