imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    version: 2.0.0-dev

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    #serializer:      { enable_annotations: false }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - MangatiBaseBundle:Form:bootstrap.html.twig
    globals:
        locale: "%locale%"
        version: "%version%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            novosga:
                type: yml
                dir: "%kernel.root_dir%/../vendor/novosga/core/Entity"
                prefix: Novosga\Entity
                alias: Novosga
                is_bundle: false
            ApiBundle:
                type: yml
                dir: "Resources/config/doctrine/"
            FOSOAuthServerBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

jms_serializer:
    enable_short_alias: false
    metadata:
        auto_detection: true
        directories:
            novosga:
                namespace_prefix: "Novosga\\Entity"
                path: "@AppBundle/Resources/config/serializer"
                
fos_oauth_server:
    db_driver: orm
    client_class:        ApiBundle\Entity\OAuthClient
    access_token_class:  ApiBundle\Entity\OAuthAccessToken
    refresh_token_class: ApiBundle\Entity\OAuthRefreshToken
    auth_code_class:     ApiBundle\Entity\OAuthAuthCode
    service:
        user_provider: novosga.user_provider

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
