app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login_check:
    path: /login_check
 
logout:
    path: /logout

#novosga_admin:
#    resource: "@NovosgaAdminBundle/Controller/"
#    type:     annotation
#    prefix: /novosga.admin

#novosga_reports:
#    resource: "@NovosgaReportsBundle/Controller/"
#    type:     annotation
#    prefix: /novosga.reports

novosga_groups:
    resource: "@NovosgaGroupsBundle/Controller/"
    type:     annotation
    prefix: /novosga.groups
    
novosga_roles:
    resource: "@NovosgaRolesBundle/Controller/"
    type:     annotation
    prefix: /novosga.roles

novosga_users:
    resource: "@NovosgaUsersBundle/Controller/"
    type:     annotation
    prefix: /novosga.users

novosga_triagem:
    resource: "@NovosgaTriagemBundle/Controller/"
    type:     annotation
    prefix: /novosga.triagem