security:

    encoders:
        md5:
            id: novosga.security.encoder.md5

    providers:
        novosga_provider:
            entity:
                class: Novosga\Entity\Usuario
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous: ~

        main:
            provider: novosga_provider
            security: true
            anonymous: false
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
