parameters:
#    parameter_name: value

services:
    novosga.routing_loader:
        class: AppBundle\Loader\RouterLoader
        arguments: ["@kernel"]
        tags:
            - { name: routing.loader }
            
    novosga.security.encoder.md5:
        class: Symfony\Component\Security\Core\Encoder\MessageDigestPasswordEncoder
        arguments: 
            algorithm: md5
            encode_as_base64: false
            iterations: 1