parameters:
#    parameter_name: value

services:
    fos_oauth_server.security.authentication.listener:
        class: ApiBundle\Security\OAuthListener
        arguments: ["@service_container"]
    
    novosga.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: ["@doctrine"]
    
    novosga.ajax_session_listener:
        class: AppBundle\Listener\AjaxSessionListener
        arguments: ['@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: kernel.request }
            
    novosga.ajax_exception_listener:
        class: AppBundle\Listener\AjaxExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 1000 }
    
    novosga.ticket_service:
        class: AppBundle\Service\TicketService
        arguments: ["@doctrine.orm.entity_manager", "@twig"]
    
    novosga.routing_loader:
        class: AppBundle\Loader\RouterLoader
        arguments: ["@kernel"]
        tags:
            - { name: routing.loader }
            
    novosga.security.listener:
        class: AppBundle\Security\SecurityListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
            
    novosga.doctrine.tableprefix:
        class: AppBundle\Extensions\Doctrine\TablePrefix
        arguments: ["%database_tableprefix%"]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, connection: default }