parameters:
#    parameter_name: value

services:
    fos_oauth_server.security.authentication.listener:
        class: ApiBundle\Security\OAuthListener
        arguments: ["@service_container"]
    
    novosga.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: ["@doctrine"]
    
    
    novosga.ticket_service:
        class: AppBundle\Service\TicketService
        arguments: ["@doctrine.orm.entity_manager", "@twig"]
    
    novosga.routing_loader:
        class: AppBundle\Loader\RouterLoader
        arguments: ["@kernel"]
        tags:
            - { name: routing.loader }
            
    novosga.security.listener:
        class: AppBundle\Security\SecurityListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
            
    novosga.security.encoder.md5:
        class: Symfony\Component\Security\Core\Encoder\MessageDigestPasswordEncoder
        arguments: 
            algorithm: md5
            encode_as_base64: false
            iterations: 1
            
    novosga.doctrine.tableprefix:
        class: AppBundle\Extensions\Doctrine\TablePrefix
        arguments: ["%database_tableprefix%"]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, connection: default }