<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHItdfI8\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHItdfI8/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHItdfI8.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerHItdfI8\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerHItdfI8\srcProdProjectContainer(array(
    'container.build_hash' => 'HItdfI8',
    'container.build_id' => 'f5c81fbd',
    'container.build_time' => 1536234370,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHItdfI8');
