<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._qVhWSY' shared service.

return $this->privates['.service_locator._qVhWSY'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('atendimento' => function (): \Novosga\Entity\Atendimento {
    return ($this->privates['.errored..service_locator._qVhWSY.Novosga\Entity\Atendimento'] ?? $this->load('getAtendimento2Service.php'));
}, 'translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}));
