<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.aRr7Km1' shared service.

return $this->privates['.service_locator.aRr7Km1'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('kernel' => function () {
    return ($this->services['kernel'] ?? $this->get('kernel', 0));
}, 'translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}));
