<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cKMjiTn' shared service.

return $this->privates['.service_locator.cKMjiTn'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('atendimento' => function (): \Novosga\Entity\Atendimento {
    return ($this->privates['.errored..service_locator.cKMjiTn.Novosga\Entity\Atendimento'] ?? $this->load('getAtendimento3Service.php'));
}, 'atendimentoService' => function (): \Novosga\Service\AtendimentoService {
    return ($this->services['Novosga\Service\AtendimentoService'] ?? $this->load('getAtendimentoServiceService.php'));
}, 'servicoService' => function (): \Novosga\Service\ServicoService {
    return ($this->services['Novosga\Service\ServicoService'] ?? $this->load('getServicoServiceService.php'));
}, 'translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}));
