<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6bFxLzq' shared service.

return $this->privates['.service_locator.6bFxLzq'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}, 'usuario' => function (): \Novosga\Entity\Usuario {
    return ($this->privates['.errored..service_locator.6bFxLzq.Novosga\Entity\Usuario'] ?? $this->load('getUsuarioService.php'));
}, 'usuarioService' => function (): \Novosga\Service\UsuarioService {
    return ($this->services['Novosga\Service\UsuarioService'] ?? $this->load('getUsuarioServiceService.php'));
}));
