<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.OivvxmE' shared service.

return $this->privates['.service_locator.OivvxmE'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('factory' => function () {
    return ($this->privates['security.encoder_factory.generic'] ?? $this->load('getSecurity_EncoderFactory_GenericService.php'));
}));
