<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Gs.xfyn' shared service.

return $this->privates['.service_locator.Gs.xfyn'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('departamento' => function (): \Novosga\Entity\Departamento {
    return ($this->privates['.errored..service_locator.Gs.xfyn.Novosga\Entity\Departamento'] ?? $this->load('getDepartamentoService.php'));
}, 'translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}));
