<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fCJLbUa' shared service.

return $this->privates['.service_locator.fCJLbUa'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('service' => function (): \App\Service\ModuleService {
    return ($this->privates['App\Service\ModuleService'] ?? $this->privates['App\Service\ModuleService'] = new \App\Service\ModuleService($this->targetDirs[3]));
}));
