<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6KCiaEP' shared service.

return $this->privates['.service_locator.6KCiaEP'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('service' => function (): \Novosga\Service\ServicoService {
    return ($this->services['Novosga\Service\ServicoService'] ?? $this->load('getServicoServiceService.php'));
}, 'unidade' => function (): \Novosga\Entity\Unidade {
    return ($this->privates['.errored..service_locator.6KCiaEP.Novosga\Entity\Unidade'] ?? $this->load('getUnidadeService.php'));
}));
