<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vIa4v.B' shared service.

return $this->privates['.service_locator.vIa4v.B'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('client' => function (): \App\Entity\OAuthClient {
    return ($this->privates['.errored..service_locator.vIa4v.B.App\Entity\OAuthClient'] ?? $this->load('getOAuthClientService.php'));
}));
