<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RpngUmH' shared service.

return $this->privates['.service_locator.RpngUmH'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('servicoService' => function (): \Novosga\Service\ServicoService {
    return ($this->services['Novosga\Service\ServicoService'] ?? $this->load('getServicoServiceService.php'));
}));
