<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8GqjtV5' shared service.

return $this->privates['.service_locator.8GqjtV5'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('servico' => function (): \Novosga\Entity\Servico {
    return ($this->privates['.errored..service_locator.8GqjtV5.Novosga\Entity\Servico'] ?? $this->load('getServicoService.php'));
}));
