<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\Admin\\AdminController::acumularAtendimentos' => function () {
    return ($this->privates['.service_locator.fOQXwLg'] ?? $this->load('get_ServiceLocator_FOQXwLgService.php'));
}, 'App\\Controller\\Admin\\AdminController::limparAtendimentos' => function () {
    return ($this->privates['.service_locator.fOQXwLg'] ?? $this->load('get_ServiceLocator_FOQXwLgService.php'));
}, 'App\\Controller\\Admin\\ApiController::removeOauthClient' => function () {
    return ($this->privates['.service_locator.vIa4v.B'] ?? $this->load('get_ServiceLocator_VIa4v_BService.php'));
}, 'App\\Controller\\Admin\\DepartamentoController::delete' => function () {
    return ($this->privates['.service_locator.Gs.xfyn'] ?? $this->load('get_ServiceLocator_Gs_XfynService.php'));
}, 'App\\Controller\\Admin\\DepartamentoController::form' => function () {
    return ($this->privates['.service_locator.lELLIAK'] ?? $this->load('get_ServiceLocator_LELLIAKService.php'));
}, 'App\\Controller\\Admin\\LocaisController::delete' => function () {
    return ($this->privates['.service_locator.heAR_C6'] ?? $this->load('get_ServiceLocator_HeARC6Service.php'));
}, 'App\\Controller\\Admin\\LocaisController::form' => function () {
    return ($this->privates['.service_locator.L3jgoLQ'] ?? $this->load('get_ServiceLocator_L3jgoLQService.php'));
}, 'App\\Controller\\Admin\\ModulosController::index' => function () {
    return ($this->privates['.service_locator.x8qx89a'] ?? $this->load('get_ServiceLocator_X8qx89aService.php'));
}, 'App\\Controller\\Admin\\ModulosController::update' => function () {
    return ($this->privates['.service_locator.fCJLbUa'] ?? $this->load('get_ServiceLocator_FCJLbUaService.php'));
}, 'App\\Controller\\Admin\\PerfisController::delete' => function () {
    return ($this->privates['.service_locator.ZN_Yxx2'] ?? $this->load('get_ServiceLocator_ZNYxx2Service.php'));
}, 'App\\Controller\\Admin\\PerfisController::form' => function () {
    return ($this->privates['.service_locator.aRr7Km1'] ?? $this->load('get_ServiceLocator_ARr7Km1Service.php'));
}, 'App\\Controller\\Admin\\PrioridadesController::delete' => function () {
    return ($this->privates['.service_locator.ezkBcJ7'] ?? $this->load('get_ServiceLocator_EzkBcJ7Service.php'));
}, 'App\\Controller\\Admin\\PrioridadesController::form' => function () {
    return ($this->privates['.service_locator.U33SBJs'] ?? $this->load('get_ServiceLocator_U33SBJsService.php'));
}, 'App\\Controller\\Admin\\ServicosController::delete' => function () {
    return ($this->privates['.service_locator.I.LcBHG'] ?? $this->load('get_ServiceLocator_I_LcBHGService.php'));
}, 'App\\Controller\\Admin\\ServicosController::form' => function () {
    return ($this->privates['.service_locator.BA06MXR'] ?? $this->load('get_ServiceLocator_BA06MXRService.php'));
}, 'App\\Controller\\Admin\\UnidadesController::delete' => function () {
    return ($this->privates['.service_locator.Vw5zKkT'] ?? $this->load('get_ServiceLocator_Vw5zKkTService.php'));
}, 'App\\Controller\\Admin\\UnidadesController::form' => function () {
    return ($this->privates['.service_locator.gGYNtR3'] ?? $this->load('get_ServiceLocator_GGYNtR3Service.php'));
}, 'App\\Controller\\Api\\AgendamentosController::post' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'App\\Controller\\Api\\FilasController::alteraStatus' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'App\\Controller\\Api\\FilasController::atendimentosUsuario' => function () {
    return ($this->privates['.service_locator.Di71Q5H'] ?? $this->load('get_ServiceLocator_Di71Q5HService.php'));
}, 'App\\Controller\\Api\\PainelController::painel' => function () {
    return ($this->privates['.service_locator.Xj_..MX'] ?? $this->load('get_ServiceLocator_Xj__MXService.php'));
}, 'App\\Controller\\Api\\TriagemController::distribui' => function () {
    return ($this->privates['.service_locator.0crVUfO'] ?? $this->load('get_ServiceLocator_0crVUfOService.php'));
}, 'App\\Controller\\Api\\TriagemController::imprimir' => function () {
    return ($this->privates['.service_locator.xxZULRR'] ?? $this->load('get_ServiceLocator_XxZULRRService.php'));
}, 'App\\Controller\\Api\\UnidadesController::atendimentos' => function () {
    return ($this->privates['.service_locator.Xj_..MX'] ?? $this->load('get_ServiceLocator_Xj__MXService.php'));
}, 'App\\Controller\\Api\\UnidadesController::servicos' => function () {
    return ($this->privates['.service_locator.6KCiaEP'] ?? $this->load('get_ServiceLocator_6KCiaEPService.php'));
}, 'App\\Controller\\DefaultController::menu' => function () {
    return ($this->privates['.service_locator.pkzMZty'] ?? $this->load('get_ServiceLocator_PkzMZtyService.php'));
}, 'App\\Controller\\DefaultController::setUnidade' => function () {
    return ($this->privates['.service_locator.Xj_..MX'] ?? $this->load('get_ServiceLocator_Xj__MXService.php'));
}, 'App\\Controller\\ProfileController::password' => function () {
    return ($this->privates['.service_locator.OivvxmE'] ?? $this->load('get_ServiceLocator_OivvxmEService.php'));
}, 'App\\Controller\\ProfileController::update' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['.service_locator.kI45avE'] ?? $this->load('get_ServiceLocator_KI45avEService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController::ajaxUpdate' => function () {
    return ($this->privates['.service_locator.dmEirDA'] ?? $this->load('get_ServiceLocator_DmEirDAService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController::chamar' => function () {
    return ($this->privates['.service_locator.hLiO.Ti'] ?? $this->load('get_ServiceLocator_HLiO_TiService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController::consultaSenha' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController::encerrar' => function () {
    return ($this->privates['.service_locator.HCrK5qt'] ?? $this->load('get_ServiceLocator_HCrK5qtService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController::index' => function () {
    return ($this->privates['.service_locator.wBnL3Wx'] ?? $this->load('get_ServiceLocator_WBnL3WxService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController::infoSenha' => function () {
    return ($this->privates['.service_locator.HCrK5qt'] ?? $this->load('get_ServiceLocator_HCrK5qtService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController::iniciar' => function () {
    return ($this->privates['.service_locator.HCrK5qt'] ?? $this->load('get_ServiceLocator_HCrK5qtService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController::naoCompareceu' => function () {
    return ($this->privates['.service_locator.HCrK5qt'] ?? $this->load('get_ServiceLocator_HCrK5qtService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController::redirecionar' => function () {
    return ($this->privates['.service_locator.HCrK5qt'] ?? $this->load('get_ServiceLocator_HCrK5qtService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController::setLocal' => function () {
    return ($this->privates['.service_locator.OBBv5TM'] ?? $this->load('get_ServiceLocator_OBBv5TMService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController::usuarios' => function () {
    return ($this->privates['.service_locator.I.LcBHG'] ?? $this->load('get_ServiceLocator_I_LcBHGService.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController::ajaxUpdate' => function () {
    return ($this->privates['.service_locator.DIkwNWx'] ?? $this->load('get_ServiceLocator_DIkwNWxService.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController::buscar' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController::cancelar' => function () {
    return ($this->privates['.service_locator.yuYEQP7'] ?? $this->load('get_ServiceLocator_YuYEQP7Service.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController::index' => function () {
    return ($this->privates['.service_locator.cOjRI41'] ?? $this->load('get_ServiceLocator_COjRI41Service.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController::infoSenha' => function () {
    return ($this->privates['.service_locator._qVhWSY'] ?? $this->load('get_ServiceLocator_QVhWSYService.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController::reativar' => function () {
    return ($this->privates['.service_locator._qVhWSY'] ?? $this->load('get_ServiceLocator_QVhWSYService.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController::transferir' => function () {
    return ($this->privates['.service_locator.cKMjiTn'] ?? $this->load('get_ServiceLocator_CKMjiTnService.php'));
}, 'Novosga\\ReportsBundle\\Controller\\DefaultController::chart' => function () {
    return ($this->privates['.service_locator.HCrK5qt'] ?? $this->load('get_ServiceLocator_HCrK5qtService.php'));
}, 'Novosga\\ReportsBundle\\Controller\\DefaultController::report' => function () {
    return ($this->privates['.service_locator.6wlOU57'] ?? $this->load('get_ServiceLocator_6wlOU57Service.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::addServico' => function () {
    return ($this->privates['.service_locator.RpngUmH'] ?? $this->load('get_ServiceLocator_RpngUmHService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::addServicoUsuario' => function () {
    return ($this->privates['.service_locator.XsDp7Mn'] ?? $this->load('get_ServiceLocator_XsDp7MnService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::index' => function () {
    return ($this->privates['.service_locator.V8sgLEy'] ?? $this->load('get_ServiceLocator_V8sgLEyService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::limparDados' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::reiniciar' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::reiniciarContador' => function () {
    return ($this->privates['.service_locator.I.LcBHG'] ?? $this->load('get_ServiceLocator_I_LcBHGService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::removeServicoUnidade' => function () {
    return ($this->privates['.service_locator.I.LcBHG'] ?? $this->load('get_ServiceLocator_I_LcBHGService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::removeServicoUsuario' => function () {
    return ($this->privates['.service_locator.XsDp7Mn'] ?? $this->load('get_ServiceLocator_XsDp7MnService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::servicos' => function () {
    return ($this->privates['.service_locator.RpngUmH'] ?? $this->load('get_ServiceLocator_RpngUmHService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::servicosUnidade' => function () {
    return ($this->privates['.service_locator.RpngUmH'] ?? $this->load('get_ServiceLocator_RpngUmHService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::updateServico' => function () {
    return ($this->privates['.service_locator.8GqjtV5'] ?? $this->load('get_ServiceLocator_8GqjtV5Service.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::updateServicoUsuario' => function () {
    return ($this->privates['.service_locator.XsDp7Mn'] ?? $this->load('get_ServiceLocator_XsDp7MnService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController::updateUsuario' => function () {
    return ($this->privates['.service_locator.6bFxLzq'] ?? $this->load('get_ServiceLocator_6bFxLzqService.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController::agendamentos' => function () {
    return ($this->privates['.service_locator.8GqjtV5'] ?? $this->load('get_ServiceLocator_8GqjtV5Service.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController::ajaxUpdate' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController::consultaSenha' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController::distribuiSenha' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController::distribuiSenhaAgendamento' => function () {
    return ($this->privates['.service_locator.ETDcPic'] ?? $this->load('get_ServiceLocator_ETDcPicService.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController::imprimir' => function () {
    return ($this->privates['.service_locator.ZQgnDOB'] ?? $this->load('get_ServiceLocator_ZQgnDOBService.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController::index' => function () {
    return ($this->privates['.service_locator.cOjRI41'] ?? $this->load('get_ServiceLocator_COjRI41Service.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController::servicoInfo' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'Novosga\\UsersBundle\\Controller\\DefaultController::form' => function () {
    return ($this->privates['.service_locator.hGFKYph'] ?? $this->load('get_ServiceLocator_HGFKYphService.php'));
}, 'Novosga\\UsersBundle\\Controller\\DefaultController::password' => function () {
    return ($this->privates['.service_locator.tsfBZIc'] ?? $this->load('get_ServiceLocator_TsfBZIcService.php'));
}, 'Novosga\\UsersBundle\\Controller\\DefaultController::perfis' => function () {
    return ($this->privates['.service_locator.t9FJQ37'] ?? $this->load('get_ServiceLocator_T9FJQ37Service.php'));
}, 'App\\Controller\\Admin\\AdminController:acumularAtendimentos' => function () {
    return ($this->privates['.service_locator.fOQXwLg'] ?? $this->load('get_ServiceLocator_FOQXwLgService.php'));
}, 'App\\Controller\\Admin\\AdminController:limparAtendimentos' => function () {
    return ($this->privates['.service_locator.fOQXwLg'] ?? $this->load('get_ServiceLocator_FOQXwLgService.php'));
}, 'App\\Controller\\Admin\\ApiController:removeOauthClient' => function () {
    return ($this->privates['.service_locator.vIa4v.B'] ?? $this->load('get_ServiceLocator_VIa4v_BService.php'));
}, 'App\\Controller\\Admin\\DepartamentoController:delete' => function () {
    return ($this->privates['.service_locator.Gs.xfyn'] ?? $this->load('get_ServiceLocator_Gs_XfynService.php'));
}, 'App\\Controller\\Admin\\DepartamentoController:form' => function () {
    return ($this->privates['.service_locator.lELLIAK'] ?? $this->load('get_ServiceLocator_LELLIAKService.php'));
}, 'App\\Controller\\Admin\\LocaisController:delete' => function () {
    return ($this->privates['.service_locator.heAR_C6'] ?? $this->load('get_ServiceLocator_HeARC6Service.php'));
}, 'App\\Controller\\Admin\\LocaisController:form' => function () {
    return ($this->privates['.service_locator.L3jgoLQ'] ?? $this->load('get_ServiceLocator_L3jgoLQService.php'));
}, 'App\\Controller\\Admin\\ModulosController:index' => function () {
    return ($this->privates['.service_locator.x8qx89a'] ?? $this->load('get_ServiceLocator_X8qx89aService.php'));
}, 'App\\Controller\\Admin\\ModulosController:update' => function () {
    return ($this->privates['.service_locator.fCJLbUa'] ?? $this->load('get_ServiceLocator_FCJLbUaService.php'));
}, 'App\\Controller\\Admin\\PerfisController:delete' => function () {
    return ($this->privates['.service_locator.ZN_Yxx2'] ?? $this->load('get_ServiceLocator_ZNYxx2Service.php'));
}, 'App\\Controller\\Admin\\PerfisController:form' => function () {
    return ($this->privates['.service_locator.aRr7Km1'] ?? $this->load('get_ServiceLocator_ARr7Km1Service.php'));
}, 'App\\Controller\\Admin\\PrioridadesController:delete' => function () {
    return ($this->privates['.service_locator.ezkBcJ7'] ?? $this->load('get_ServiceLocator_EzkBcJ7Service.php'));
}, 'App\\Controller\\Admin\\PrioridadesController:form' => function () {
    return ($this->privates['.service_locator.U33SBJs'] ?? $this->load('get_ServiceLocator_U33SBJsService.php'));
}, 'App\\Controller\\Admin\\ServicosController:delete' => function () {
    return ($this->privates['.service_locator.I.LcBHG'] ?? $this->load('get_ServiceLocator_I_LcBHGService.php'));
}, 'App\\Controller\\Admin\\ServicosController:form' => function () {
    return ($this->privates['.service_locator.BA06MXR'] ?? $this->load('get_ServiceLocator_BA06MXRService.php'));
}, 'App\\Controller\\Admin\\UnidadesController:delete' => function () {
    return ($this->privates['.service_locator.Vw5zKkT'] ?? $this->load('get_ServiceLocator_Vw5zKkTService.php'));
}, 'App\\Controller\\Admin\\UnidadesController:form' => function () {
    return ($this->privates['.service_locator.gGYNtR3'] ?? $this->load('get_ServiceLocator_GGYNtR3Service.php'));
}, 'App\\Controller\\Api\\AgendamentosController:post' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'App\\Controller\\Api\\FilasController:alteraStatus' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'App\\Controller\\Api\\FilasController:atendimentosUsuario' => function () {
    return ($this->privates['.service_locator.Di71Q5H'] ?? $this->load('get_ServiceLocator_Di71Q5HService.php'));
}, 'App\\Controller\\Api\\PainelController:painel' => function () {
    return ($this->privates['.service_locator.Xj_..MX'] ?? $this->load('get_ServiceLocator_Xj__MXService.php'));
}, 'App\\Controller\\Api\\TriagemController:distribui' => function () {
    return ($this->privates['.service_locator.0crVUfO'] ?? $this->load('get_ServiceLocator_0crVUfOService.php'));
}, 'App\\Controller\\Api\\TriagemController:imprimir' => function () {
    return ($this->privates['.service_locator.xxZULRR'] ?? $this->load('get_ServiceLocator_XxZULRRService.php'));
}, 'App\\Controller\\Api\\UnidadesController:atendimentos' => function () {
    return ($this->privates['.service_locator.Xj_..MX'] ?? $this->load('get_ServiceLocator_Xj__MXService.php'));
}, 'App\\Controller\\Api\\UnidadesController:servicos' => function () {
    return ($this->privates['.service_locator.6KCiaEP'] ?? $this->load('get_ServiceLocator_6KCiaEPService.php'));
}, 'App\\Controller\\DefaultController:menu' => function () {
    return ($this->privates['.service_locator.pkzMZty'] ?? $this->load('get_ServiceLocator_PkzMZtyService.php'));
}, 'App\\Controller\\DefaultController:setUnidade' => function () {
    return ($this->privates['.service_locator.Xj_..MX'] ?? $this->load('get_ServiceLocator_Xj__MXService.php'));
}, 'App\\Controller\\ProfileController:password' => function () {
    return ($this->privates['.service_locator.OivvxmE'] ?? $this->load('get_ServiceLocator_OivvxmEService.php'));
}, 'App\\Controller\\ProfileController:update' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['.service_locator.kI45avE'] ?? $this->load('get_ServiceLocator_KI45avEService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController:ajaxUpdate' => function () {
    return ($this->privates['.service_locator.dmEirDA'] ?? $this->load('get_ServiceLocator_DmEirDAService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController:chamar' => function () {
    return ($this->privates['.service_locator.hLiO.Ti'] ?? $this->load('get_ServiceLocator_HLiO_TiService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController:consultaSenha' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController:encerrar' => function () {
    return ($this->privates['.service_locator.HCrK5qt'] ?? $this->load('get_ServiceLocator_HCrK5qtService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController:index' => function () {
    return ($this->privates['.service_locator.wBnL3Wx'] ?? $this->load('get_ServiceLocator_WBnL3WxService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController:infoSenha' => function () {
    return ($this->privates['.service_locator.HCrK5qt'] ?? $this->load('get_ServiceLocator_HCrK5qtService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController:iniciar' => function () {
    return ($this->privates['.service_locator.HCrK5qt'] ?? $this->load('get_ServiceLocator_HCrK5qtService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController:naoCompareceu' => function () {
    return ($this->privates['.service_locator.HCrK5qt'] ?? $this->load('get_ServiceLocator_HCrK5qtService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController:redirecionar' => function () {
    return ($this->privates['.service_locator.HCrK5qt'] ?? $this->load('get_ServiceLocator_HCrK5qtService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController:setLocal' => function () {
    return ($this->privates['.service_locator.OBBv5TM'] ?? $this->load('get_ServiceLocator_OBBv5TMService.php'));
}, 'Novosga\\AttendanceBundle\\Controller\\DefaultController:usuarios' => function () {
    return ($this->privates['.service_locator.I.LcBHG'] ?? $this->load('get_ServiceLocator_I_LcBHGService.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController:ajaxUpdate' => function () {
    return ($this->privates['.service_locator.DIkwNWx'] ?? $this->load('get_ServiceLocator_DIkwNWxService.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController:buscar' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController:cancelar' => function () {
    return ($this->privates['.service_locator.yuYEQP7'] ?? $this->load('get_ServiceLocator_YuYEQP7Service.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController:index' => function () {
    return ($this->privates['.service_locator.cOjRI41'] ?? $this->load('get_ServiceLocator_COjRI41Service.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController:infoSenha' => function () {
    return ($this->privates['.service_locator._qVhWSY'] ?? $this->load('get_ServiceLocator_QVhWSYService.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController:reativar' => function () {
    return ($this->privates['.service_locator._qVhWSY'] ?? $this->load('get_ServiceLocator_QVhWSYService.php'));
}, 'Novosga\\MonitorBundle\\Controller\\DefaultController:transferir' => function () {
    return ($this->privates['.service_locator.cKMjiTn'] ?? $this->load('get_ServiceLocator_CKMjiTnService.php'));
}, 'Novosga\\ReportsBundle\\Controller\\DefaultController:chart' => function () {
    return ($this->privates['.service_locator.HCrK5qt'] ?? $this->load('get_ServiceLocator_HCrK5qtService.php'));
}, 'Novosga\\ReportsBundle\\Controller\\DefaultController:report' => function () {
    return ($this->privates['.service_locator.6wlOU57'] ?? $this->load('get_ServiceLocator_6wlOU57Service.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:addServico' => function () {
    return ($this->privates['.service_locator.RpngUmH'] ?? $this->load('get_ServiceLocator_RpngUmHService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:addServicoUsuario' => function () {
    return ($this->privates['.service_locator.XsDp7Mn'] ?? $this->load('get_ServiceLocator_XsDp7MnService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:index' => function () {
    return ($this->privates['.service_locator.V8sgLEy'] ?? $this->load('get_ServiceLocator_V8sgLEyService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:limparDados' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:reiniciar' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:reiniciarContador' => function () {
    return ($this->privates['.service_locator.I.LcBHG'] ?? $this->load('get_ServiceLocator_I_LcBHGService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:removeServicoUnidade' => function () {
    return ($this->privates['.service_locator.I.LcBHG'] ?? $this->load('get_ServiceLocator_I_LcBHGService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:removeServicoUsuario' => function () {
    return ($this->privates['.service_locator.XsDp7Mn'] ?? $this->load('get_ServiceLocator_XsDp7MnService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:servicos' => function () {
    return ($this->privates['.service_locator.RpngUmH'] ?? $this->load('get_ServiceLocator_RpngUmHService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:servicosUnidade' => function () {
    return ($this->privates['.service_locator.RpngUmH'] ?? $this->load('get_ServiceLocator_RpngUmHService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:updateServico' => function () {
    return ($this->privates['.service_locator.8GqjtV5'] ?? $this->load('get_ServiceLocator_8GqjtV5Service.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:updateServicoUsuario' => function () {
    return ($this->privates['.service_locator.XsDp7Mn'] ?? $this->load('get_ServiceLocator_XsDp7MnService.php'));
}, 'Novosga\\SettingsBundle\\Controller\\DefaultController:updateUsuario' => function () {
    return ($this->privates['.service_locator.6bFxLzq'] ?? $this->load('get_ServiceLocator_6bFxLzqService.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController:agendamentos' => function () {
    return ($this->privates['.service_locator.8GqjtV5'] ?? $this->load('get_ServiceLocator_8GqjtV5Service.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController:ajaxUpdate' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController:consultaSenha' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController:distribuiSenha' => function () {
    return ($this->privates['.service_locator.gRkHsSG'] ?? $this->load('get_ServiceLocator_GRkHsSGService.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController:distribuiSenhaAgendamento' => function () {
    return ($this->privates['.service_locator.ETDcPic'] ?? $this->load('get_ServiceLocator_ETDcPicService.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController:imprimir' => function () {
    return ($this->privates['.service_locator.ZQgnDOB'] ?? $this->load('get_ServiceLocator_ZQgnDOBService.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController:index' => function () {
    return ($this->privates['.service_locator.cOjRI41'] ?? $this->load('get_ServiceLocator_COjRI41Service.php'));
}, 'Novosga\\TriageBundle\\Controller\\DefaultController:servicoInfo' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'Novosga\\UsersBundle\\Controller\\DefaultController:form' => function () {
    return ($this->privates['.service_locator.hGFKYph'] ?? $this->load('get_ServiceLocator_HGFKYphService.php'));
}, 'Novosga\\UsersBundle\\Controller\\DefaultController:password' => function () {
    return ($this->privates['.service_locator.tsfBZIc'] ?? $this->load('get_ServiceLocator_TsfBZIcService.php'));
}, 'Novosga\\UsersBundle\\Controller\\DefaultController:perfis' => function () {
    return ($this->privates['.service_locator.t9FJQ37'] ?? $this->load('get_ServiceLocator_T9FJQ37Service.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
