<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.Di71Q5H.Novosga\Entity\Unidade' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.Di71Q5H": it references class "Novosga\\Entity\\Unidade" but no such service exists.');
