Novosga\Entity\AbstractAtendimento:
    type: mappedSuperclass
    table: abstract_atendimento
    fields:
        local:
            type: smallint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: num_local
        dataAgendamento:
            type: datetime
            nullable: true
            column: dt_age
        dataChegada:
            type: datetime
            nullable: false
            column: dt_cheg
        dataChamada:
            type: datetime
            nullable: true
            column: dt_cha
        dataInicio:
            type: datetime
            nullable: true
            column: dt_ini
        dataFim:
            type: datetime
            nullable: true
            column: dt_fim
        status:
            type: smallint
            length: 50
            nullable: false
        nomeCliente:
            type: string
            length: 100
            nullable: true
            column: nm_cli
        documentoCliente:
            type: string
            length: 20
            unique: false
            nullable: true
            column: ident_cli
        siglaSenha:
            type: string
            length: 3
            nullable: false
            column: sigla_senha
        numeroSenha:
            type: integer
            length: null
            nullable: false
            column: num_senha
    manyToOne:
        unidade:
            targetEntity: Novosga\Entity\Unidade
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                unidade_id:
                    referencedColumnName: id
            orphanRemoval: false
        servico:
            targetEntity: Novosga\Entity\Servico
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                servico_id:
                    referencedColumnName: id
            orphanRemoval: false
        servicoUnidade:
            targetEntity: Novosga\Entity\ServicoUnidade
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                servico_id:
                    referencedColumnName: servico_id
                unidade_id:
                    referencedColumnName: unidade_id
            orphanRemoval: false
        prioridade:
            targetEntity: Novosga\Entity\Prioridade
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                prioridade_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Novosga\Entity\Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuarioTriagem:
            targetEntity: Novosga\Entity\Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_tri_id:
                    referencedColumnName: id
            orphanRemoval: false
        pai:
            targetEntity: Novosga\Entity\Atendimento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                atendimento_id:
                    referencedColumnName: id
            orphanRemoval: false
