Novosga\Entity\AtendimentoMeta:
    type: entity
    table: atend_meta
    id:
        atendimento:
            associationKey: true
    manyToOne:
        atendimento:
            targetEntity: Novosga\Entity\Atendimento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                atendimento_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
