Novosga\Entity\Atendimento:
    type: entity
    table: atendimentos
    oneToMany:
        codificados:
            targetEntity: Novosga\Entity\AtendimentoCodificado
            cascade: {  }
            fetch: LAZY
            mappedBy: atendimento
            inversedBy: null
            orphanRemoval: false
            orderBy: null
