Novosga\Entity\AtendimentoCodificado:
    type: entity
    table: atend_codif
    id:
        atendimento:
            associationKey: true
    fields:
        peso:
            type: smallint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: valor_peso
    manyToOne:
        atendimento:
            targetEntity: Novosga\Entity\Atendimento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                atendimento_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
