Novosga\Entity\AtendimentoHistoricoMeta:
    type: entity
    table: historico_atend_meta
    id:
        atendimento:
            associationKey: true
    manyToOne:
        atendimento:
            targetEntity: Novosga\Entity\AtendimentoHistorico
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                atendimento_id:
                    referencedColumnName: id
            orphanRemoval: false
