Novosga\Entity\Cargo:
    type: entity
    table: cargos
    repositoryClass: AppBundle\Repository\ORM\CargoRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            scale: 0
            length: 50
            unique: false
            nullable: false
            precision: 0
        descricao:
            type: string
            scale: 0
            length: 150
            unique: false
            nullable: false
            precision: 0
        modulos:
            type: simple_array
            nullable: true
