Novosga\Entity\Cargo:
    type: entity
    table: cargos
    repositoryClass: Novosga\Repository\CargoRepository
    id:
        id:
          type: integer
          generator:
            strategy: IDENTITY
    fields:
        nome:
            type: string
            scale: 0
            length: 50
            unique: false
            nullable: false
            precision: 0
        descricao:
            type: string
            scale: 0
            length: 150
            unique: false
            nullable: false
            precision: 0
    manyToMany:
        modulos:
            targetEntity: Modulo
            joinTable:
              name: cargos_mod_perm
              joinColumns:
                cargo_id:
                  referencedColumnName: id
              inverseJoinColumns:
                modulo_id:
                  referencedColumnName: id
