Novosga\Entity\Contador:
    type: entity
    table: contador
    id:
        unidade:
            associationKey: true
    fields:
        minimo:
            type: integer
            nullable: false
        maximo:
            type: integer
            nullable: true
        incremento:
            type: integer
            nullable: false
        atual:
            type: integer
            nullable: false
    oneToOne:
        unidade:
            targetEntity: Novosga\Entity\Unidade
            fetch: LAZY
            joinColumns:
                unidade_id:
                    referencedColumnName: id
        servico:
            targetEntity: Novosga\Entity\Servico
            fetch: LAZY
            joinColumns:
                servico_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
