AppBundle\Entity\Contador:
    type: entity
    table: contador
    id:
        unidade:
            associationKey: true
    fields:
        minimo:
            type: integer
            nullable: false
        maximo:
            type: integer
            nullable: true
        incremento:
            type: integer
            nullable: false
        atual:
            type: integer
            nullable: false
    oneToOne:
        unidade:
            targetEntity: AppBundle\Entity\Unidade
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: contador
            joinColumns:
                unidade_id:
                    referencedColumnName: id
            orphanRemoval: false
        servico:
            targetEntity: AppBundle\Entity\Servico
            fetch: LAZY
            joinColumns:
                servico_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
