Novosga\Entity\Grupo:
    type: entity
    table: grupos
    repositoryClass: AppBundle\Repository\ORM\GrupoRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            scale: 0
            length: 50
            unique: false
            nullable: false
            precision: 0
        descricao:
            type: string
            scale: 0
            length: 150
            unique: false
            nullable: false
            precision: 0
        left:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: esquerda
        right:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: direita
        level:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: nivel
    oneToOne:
        unidade:
            targetEntity: Novosga\Entity\Unidade
            cascade: {  }
            fetch: LAZY
            mappedBy: grupo
            inversedBy: null
            joinColumns: {  }
            orphanRemoval: false
    manyToOne:
        parent:
            targetEntity: Novosga\Entity\Grupo
            fetch: LAZY
            joinColumns: {  }
    lifecycleCallbacks: {  }
