Novosga\Entity\Lotacao:
    type: entity
    table: usuarios_unidades_cargos
    repositoryClass: AppBundle\Repository\ORM\LotacaoRepository
    id:
        usuario:
            associationKey: true
        unidade:
            associationKey: true
    manyToOne:
        usuario:
            targetEntity: Novosga\Entity\Usuario
            cascade: {  }
            fetch: LAZY
            inversedBy: lotacoes
            joinColumns:
                usuario_id:
                    referencedColumnName: id
        unidade:
            targetEntity: Novosga\Entity\Unidade
            cascade: {  }
            fetch: LAZY
            joinColumns:
                unidade_id:
                    referencedColumnName: id
        cargo:
            targetEntity: Novosga\Entity\Cargo
            cascade: {  }
            fetch: LAZY
            joinColumns:
                cargo_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
