Novosga\Entity\Metadata:
    type: mappedSuperclass
    id:
        name:
            type: string
            length: 50
            nullable: false
            id: true
    fields:
        value:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            columnDefinition: text