Novosga\Entity\Metadata:
    type: mappedSuperclass
    id:
        name:
            type: string
            length: 50
            nullable: false
            id: true
    fields:
        value:
            type: json
            nullable: false