AppBundle\Entity\Permissao:
    type: entity
    table: cargos_mod_perm
    repositoryClass: Novosga\Repository\PermissaoRepository
    id:
        modulo:
            associationKey: true
        cargo:
            associationKey: true
    fields:
        permissao:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        modulo:
            targetEntity: AppBundle\Entity\Modulo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                modulo_id:
                    referencedColumnName: id
            orphanRemoval: false
        cargo:
            targetEntity: AppBundle\Entity\Cargo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: permissoes
            joinColumns:
                cargo_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
