Novosga\Entity\Prioridade:
    type: entity
    table: prioridades
    repositoryClass: Novosga\Repository\PrioridadeRepository
    fields:
        nome:
            type: string
            scale: 0
            length: 64
            unique: false
            nullable: false
            precision: 0
        descricao:
            type: string
            scale: 0
            length: 100
            unique: false
            nullable: false
            precision: 0
        peso:
            type: smallint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        status:
            type: smallint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
