Novosga\Entity\ServicoUnidade:
    type: entity
    table: servicos_unidades
    id:
        servico:
            associationKey: true
        unidade:
            associationKey: true
    fields:
        sigla:
            type: string
            length: 3
            unique: false
            nullable: false
            precision: 0
        status:
            type: smallint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        peso:
            type: smallint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        prioridade:
            type: boolean
            nullable: false
        numeroInicial:
            name: numero_inicial
            type: integer
            nullable: false
        numeroFinal:
            name: numero_final
            type: integer
            nullable: true
        incremento:
            type: integer
            nullable: false
        horaInicio:
            name: hora_inicio
            type: time
            nullable: true
        horaFim:
            name: hora_fim
            type: time
            nullable: true
        tempoAtendimento:
            name: tempo_atendimento
            type: integer
            nullable: true
        maximoAtendimentos:
            name: max_atendimentos
            type: integer
            nullable: true
    manyToOne:
        servico:
            targetEntity: Novosga\Entity\Servico
            fetch: LAZY
            inversedBy: servicosUnidade
            joinColumns:
                servico_id:
                    referencedColumnName: id
            orphanRemoval: false
        unidade:
            targetEntity: Novosga\Entity\Unidade
            fetch: LAZY
            joinColumns:
                unidade_id:
                    referencedColumnName: id
            orphanRemoval: false
        local:
            targetEntity: Novosga\Entity\Local
            cascade: {  }
            fetch: LAZY
            joinColumns:
                local_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
