Novosga\Entity\ServicoMeta:
    type: entity
    table: serv_meta
    id:
        servico:
            associationKey: true
    manyToOne:
        servico:
            targetEntity: Novosga\Entity\Servico
            cascade: {  }
            fetch: LAZY
            joinColumns:
                servico_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
