Novosga\Entity\Servico:
    type: entity
    table: servicos
    repositoryClass: Novosga\Repository\ServicoRepository
    id:
        id:
          type: integer
          generator:
            strategy: IDENTITY
    fields:
        nome:
            type: string
            length: 50
            unique: false
            nullable: false
        descricao:
            type: string
            length: 100
            unique: false
            nullable: false
        status:
            type: boolean
            unique: false
            nullable: false
        peso:
            type: smallint
            unique: false
            nullable: false
    manyToOne:
        mestre:
            targetEntity: Novosga\Entity\Servico
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: subServicos
            joinColumns:
                macro_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        subServicos:
            targetEntity: Novosga\Entity\Servico
            cascade: {  }
            fetch: LAZY
            mappedBy: mestre
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        servicosUnidade:
            targetEntity: Novosga\Entity\ServicoUnidade
            cascade: {  }
            fetch: LAZY
            mappedBy: servico
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
