Novosga\Entity\ServicoMeta:
    type: entity
    table: serv_meta
    id:
        name:
            type: string
            length: 50
            nullable: false
            id: true
        servico:
            associationKey: true
    fields:
        value:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            columnDefinition: text
    manyToOne:
        servico:
            targetEntity: Novosga\Entity\Servico
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                servico_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
