Novosga\Entity\Unidade:
    type: entity
    table: unidades
    repositoryClass: Novosga\Repository\UnidadeRepository
    fields:
        codigo:
            type: string
            length: 10
            unique: true
            nullable: false
        nome:
            type: string
            length: 50
            unique: false
            nullable: false
        status:
            type: boolean
            unique: false
            nullable: false
        mensagemImpressao:
            type: string
            length: 100
            unique: false
            nullable: false
            column: msg_imp
    oneToOne:
        grupo:
            targetEntity: Novosga\Entity\Grupo
            fetch: EAGER
            inversedBy: unidade
            joinColumns:
                grupo_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
