Novosga\Entity\Unidade:
    type: entity
    table: unidades
    repositoryClass: AppBundle\Repository\ORM\UnidadeRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        codigo:
            type: string
            length: 10
            unique: true
            nullable: false
        nome:
            type: string
            length: 50
            unique: false
            nullable: false
        status:
            type: boolean
            unique: false
            nullable: false
        mensagemImpressao:
            type: string
            length: 100
            unique: false
            nullable: false
            column: mensagem
