Novosga\Entity\UniqueId:
    type: mappedSuperclass
    id:
        id:
            type: integer
            primary: true
            unique: true
            nullable: false
            generator:
                strategy: IDENTITY