AppBundle\Entity\UsuarioMeta:
    type: entity
    table: usu_meta
    id:
        name:
            type: string
            scale: 0
            length: 50
            unique: false
            nullable: false
            precision: 0
            id: true
    fields:
        value:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            columnDefinition: text
    manyToOne:
        usuario:
            targetEntity: AppBundle\Entity\Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
