Novosga\Entity\UsuarioMeta:
    type: entity
    table: usu_meta
    id:
        usuario:
            associationKey: true
    manyToOne:
        usuario:
            targetEntity: Novosga\Entity\Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
