AppBundle\Entity\Usuario:
    type: entity
    table: usuarios
    repositoryClass: Novosga\Repository\UsuarioRepository
    fields:
        login:
            type: string
            scale: 0
            length: 20
            unique: true
            nullable: false
            precision: 0
        nome:
            type: string
            scale: 0
            length: 20
            unique: false
            nullable: false
            precision: 0
        sobrenome:
            type: string
            scale: 0
            length: 100
            unique: false
            nullable: false
            precision: 0
        senha:
            type: string
            scale: 0
            length: 128
            unique: false
            nullable: false
            precision: 0
        status:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        ultimoAcesso:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: ult_acesso
        sessionId:
            type: string
            scale: 0
            length: 50
            unique: false
            nullable: true
            precision: 0
            column: session_id
        algorithm:
            type: string
            scale: 0
            length: 10
            unique: false
            nullable: false
            precision: 0
    oneToMany:
        lotacoes:
            targetEntity: AppBundle\Entity\Lotacao
            cascade: {  }
            fetch: LAZY
            mappedBy: usuario
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
