<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJgRsXxu\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJgRsXxu/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJgRsXxu.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJgRsXxu\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJgRsXxu\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JgRsXxu',
    'container.build_id' => 'd1068a20',
    'container.build_time' => 1536179477,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJgRsXxu');
