Novosga\Entity\Unidade:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: codigo
            message: J치 existe uma unidade com esse c칩digo
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: nome
            message: J치 existe uma unidade com esse c칩digo
    properties:
        codigo:
            - NotBlank: ~
            - Length:
                max: 10
        nome:
            - NotBlank: ~
            - Length:
                max: 20
                min: 3
        ativo:
            - NotNull: ~
