Novosga\Entity\Configuracao:
    type: entity
    table: config
    id:
        chave:
            type: string
            scale: 0
            length: 150
            unique: false
            nullable: false
            precision: 0
            id: true
    fields:
        valor:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        tipo:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
