<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pkzMZty' shared service.

return $this->privates['.service_locator.pkzMZty'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('kernel' => function () {
    return ($this->services['kernel'] ?? $this->get('kernel', 0));
}));
