<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Vw5zKkT' shared service.

return $this->privates['.service_locator.Vw5zKkT'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}, 'unidade' => function (): \Novosga\Entity\Unidade {
    return ($this->privates['.errored..service_locator.Vw5zKkT.Novosga\Entity\Unidade'] ?? $this->load('getUnidade3Service.php'));
}));
