<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ezkBcJ7' shared service.

return $this->privates['.service_locator.ezkBcJ7'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('prioridade' => function (): \Novosga\Entity\Prioridade {
    return ($this->privates['.errored..service_locator.ezkBcJ7.Novosga\Entity\Prioridade'] ?? $this->load('getPrioridadeService.php'));
}, 'translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}));
