<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hLiO.Ti' shared service.

return $this->privates['.service_locator.hLiO.Ti'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('atendimentoService' => function (): \Novosga\Service\AtendimentoService {
    return ($this->services['Novosga\Service\AtendimentoService'] ?? $this->load('getAtendimentoServiceService.php'));
}, 'filaService' => function (): \Novosga\Service\FilaService {
    return ($this->services['Novosga\Service\FilaService'] ?? $this->load('getFilaServiceService.php'));
}, 'translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}, 'usuarioService' => function (): \Novosga\Service\UsuarioService {
    return ($this->services['Novosga\Service\UsuarioService'] ?? $this->load('getUsuarioServiceService.php'));
}));
