<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZN_Yxx2' shared service.

return $this->privates['.service_locator.ZN_Yxx2'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('perfil' => function (): \Novosga\Entity\Perfil {
    return ($this->privates['.errored..service_locator.ZN_Yxx2.Novosga\Entity\Perfil'] ?? $this->load('getPerfilService.php'));
}, 'translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}));
