<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Xj_..MX' shared service.

return $this->privates['.service_locator.Xj_..MX'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('unidade' => function (): \Novosga\Entity\Unidade {
    return ($this->privates['.errored..service_locator.Xj_..MX.Novosga\Entity\Unidade'] ?? $this->load('getUnidade4Service.php'));
}));
