<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Di71Q5H' shared service.

return $this->privates['.service_locator.Di71Q5H'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('filaService' => function (): \Novosga\Service\FilaService {
    return ($this->services['Novosga\Service\FilaService'] ?? $this->load('getFilaServiceService.php'));
}, 'unidade' => function (): \Novosga\Entity\Unidade {
    return ($this->privates['.errored..service_locator.Di71Q5H.Novosga\Entity\Unidade'] ?? $this->load('getUnidade2Service.php'));
}, 'usuarioService' => function (): \Novosga\Service\UsuarioService {
    return ($this->services['Novosga\Service\UsuarioService'] ?? $this->load('getUsuarioServiceService.php'));
}));
