<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wBnL3Wx' shared service.

return $this->privates['.service_locator.wBnL3Wx'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('atendimentoService' => function (): \Novosga\Service\AtendimentoService {
    return ($this->services['Novosga\Service\AtendimentoService'] ?? $this->load('getAtendimentoServiceService.php'));
}, 'securityService' => function (): \App\Service\SecurityService {
    return ($this->privates['App\Service\SecurityService'] ?? $this->privates['App\Service\SecurityService'] = new \App\Service\SecurityService($this->targetDirs[3]));
}, 'servicoService' => function (): \Novosga\Service\ServicoService {
    return ($this->services['Novosga\Service\ServicoService'] ?? $this->load('getServicoServiceService.php'));
}, 'translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}, 'usuarioService' => function (): \Novosga\Service\UsuarioService {
    return ($this->services['Novosga\Service\UsuarioService'] ?? $this->load('getUsuarioServiceService.php'));
}));
