<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tsfBZIc' shared service.

return $this->privates['.service_locator.tsfBZIc'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('user' => function (): \Novosga\Entity\Usuario {
    return ($this->privates['.errored..service_locator.tsfBZIc.Novosga\Entity\Usuario'] ?? $this->load('getUsuario3Service.php'));
}));
