<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.heAR_C6' shared service.

return $this->privates['.service_locator.heAR_C6'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('local' => function (): \Novosga\Entity\Local {
    return ($this->privates['.errored..service_locator.heAR_C6.Novosga\Entity\Local'] ?? $this->load('getLocalService.php'));
}, 'translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}));
