<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator._qVhWSY.Novosga\Entity\Atendimento' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator._qVhWSY": it references class "Novosga\\Entity\\Atendimento" but no such service exists.');
