<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Novosga\Service\Configuration' shared autowired service.

include_once $this->targetDirs[3].'/vendor/novosga/core/Service/Configuration.php';

return $this->privates['Novosga\Service\Configuration'] = new \Novosga\Service\Configuration($this->targetDirs[3]);
