<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.heAR_C6.Novosga\Entity\Local' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.heAR_C6": it references class "Novosga\\Entity\\Local" but no such service exists.');
