<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.t9FJQ37.Novosga\Entity\Perfil' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.t9FJQ37": it references class "Novosga\\Entity\\Perfil" but no such service exists.');
