<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.6bFxLzq.Novosga\Entity\Usuario' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.6bFxLzq": it references class "Novosga\\Entity\\Usuario" but no such service exists.');
